name: ISOs

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 1 */2 *'

jobs:
  build:
    runs-on: ubuntu-24.04
    container: 
      image: quay.io/fedora/fedora:42
      options: --privileged
    strategy:
      matrix:
        images:
          - type: silverblue
            container_url: quay.io/fedora/fedora-silverblue
          - type: kinoite
            container_url: quay.io/fedora/fedora-kinoite
          - type: xfce-atomic
            container_url: quay.io/fedora-ostree-desktops/xfce-atomic
    steps:
      - name: Install dependencies
        run: dnf install git lorax util-linux curl skopeo -y
      - uses: actions/checkout@v4
      - name: Make output folder
        run: mkdir output
      - name: Download Fedora ISO
        run: curl -Lso base.iso https://dl.fedoraproject.org/pub/fedora/linux/releases/42/Everything/x86_64/os/images/boot.iso
      - name: Download container
        run: skopeo copy docker://${{matrix.images.container_url}}:42 oci:container
      - name: Build ISO
        run: mkksiso -a container kickstart.${{matrix.images.type}} base.iso output/image-42.iso
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.images.type}}
          path: output/image-42.iso
