name: ISOs

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 1 */3 *'

jobs:
  build:
    runs-on: ubuntu-24.04
    container: quay.io/fedora/fedora:41
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: dnf install lorax util-linux curl skopeo -y
      - name: Make folders
        run: mkdir output silverblue xfce-atomic
      - name: Download Fedora ISO
        run: curl -Lso base.iso https://dl.fedoraproject.org/pub/fedora/linux/releases/41/Everything/x86_64/os/images/boot.iso
      - name: Download Silverblue container
        run: skopeo copy docker://quay.io/fedora/fedora-silverblue:41 oci:silverblue
      - name: Download XFCE Atomic container
        run: skopeo copy docker://quay.io/fedora-ostree-desktops/xfce-atomic:41 oci:xfce-atomic
      - name: Build Silverblue ISO
        run: mkksiso -a silverblue kickstart.silverblue base.iso output/silverblue-41.iso
      - name: Build XFCE Atomic ISO
        run: mkksiso -a xfce-atomic kickstart.xfce-atomic base.iso output/xfce-atomic-41.iso
      - name: Upload Silverblue ISO
        uses: actions/upload-artifact@v4
        with:
          name: silverblue
          path: output/silverblue-41.iso
      - name: Upload XFCE Atomic ISO
        uses: actions/upload-artifact@v4
        with:
          name: xfce-atomic
          path: output/xfce-atomic-41.iso
